In [1]:
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.ticker import AutoMinorLocator
from scipy.optimize import curve_fit
from decimal import Decimal

In [2]:
#Define graphing constants
page = (19,10)
single_title = 'Light Intensity of Single Slit Diffraction Pattern'
double_title = 'Light Intensity of Double Slit Interference Pattern'

#Global variables
I, offset, length = 1.0, 0.07, 1.0

In [3]:
#Calculate accurate floating point uncertainties using the Decimal module

#Uncertainty percentages recorded from 
#https://www.pasco.com/file_downloads/Downloads_Manuals/PASPORT-High-Sensitivity-Light-Sensor-Manual-PS-2176.pdf
a_slow = 0.0001

''' Finds the first significant digit in Decimal object n.
'''
def firstdigit(n):
    abs_n = abs(n)
    place = 0
    if (abs_n >= Decimal('1.0')):
        while (abs_n >= Decimal('10.0')):
            abs_n = Decimal.shift(abs_n, -1)
            place -= 1
    else:
        while (abs_n < Decimal('1.0')):
            abs_n = Decimal.shift(abs_n, 1)
            place += 1
    return round(n, place)

''' Finds the last significant digit in Decimal object n.
'''
def lastdigit(n):
    place = 0
    while (n % Decimal('1.0') == Decimal('0.0')):
        n = Decimal.shift(n, -1)
    while (n % Decimal('1.0') != Decimal('0.0')):
        n = Decimal.shift(n, 1)
        place -= 1
    return place

''' Calculates the maximum uncertainty by taking the larger between the error of
    accuracy and the error of precision.
    Error of accuracy is rounded to one significant digit.
'''
def finderror(x, a):
    dec_x = Decimal(str(np.abs(x)))
    dec_a = Decimal(str(a))
    err_a = firstdigit(dec_x * dec_a)
    err_p = Decimal('1.0') * Decimal(str(10.0**(lastdigit(dec_x))))
    return (float)(max(err_a, err_p))

In [37]:
''' Model function for single slit intensity pattern
'''
def intensity_s(x, a):
    phi = (np.pi * a)/wavelength * ((x + offset)/np.sqrt((x + offset)**2 + length**2))
    return I * (np.sin(phi)/phi)**2

''' Model function for double slit diffraction pattern
'''
def intensity_d(x, a, d):
    phi_s = (np.pi * a)/wavelength * ((x + offset)/np.sqrt((x + offset)**2 + length**2))
    phi_d = (np.pi * d)/wavelength * ((x + offset)/np.sqrt((x + offset)**2 + length**2))
    return I * (np.cos(phi_d))**2 * (np.sin(phi_s)/phi_s)**2

''' Saves a graph to directory/filename.png with standard options.
'''
def makegraph(x, y, title, filename, color='red', linewidth=0.4, figsize=page, xlabel='Sensor Position (m)',
              ylabel='Light Intensity (V)', directory='graphs/', show_legend=False, label=None,
              plotsecond=False, secondset=(None, None), secondlabel=None, u=None):
    plt.figure(figsize=figsize)
    if u == None: plt.plot(x, y, color=color, linewidth=linewidth, label=label)
    else: plt.errorbar(x, y, yerr=u, ecolor=color, elinewidth=1.0, capthick=1.0, capsize=2.0, fmt='none', label=label)
    if plotsecond: plt.plot(secondset[0], secondset[1], color='#197cff', linewidth=linewidth+0.6, label=secondlabel)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    if show_legend: plt.legend()
    #plt.show()
    plt.savefig(directory+filename+'.png', bbox_inches='tight')
    plt.clf()

''' Calls makegraph with optimum values and best fit data
'''
def makegraphfit(i, title, filename, which, popt, u=None):
    space = np.linspace(-0.13, 0.0, 1000)
    global I
    global offset
    global length
    if (which == 'single'):
        I, offset, length = I_s[i], offset_s[i], length_s
        makegraph(single[i][:,0], single[i][:,1], title, filename, 
                  plotsecond=True, secondset=(space, intensity_s(space, popt)), 
                  show_legend=True, label='data', secondlabel='best fit', u=u)
    else:
        I, offset, length = I_d[i], offset_d[i], length_d
        makegraph(double[i][:,0], double[i][:,1], title, filename,
                  plotsecond=True, secondset=(space, intensity_d(space, popt[0], popt[1])), 
                  show_legend=True, label='data', secondlabel='best fit', u=u)

In [65]:
#Load the collected data
single, double, u_s, u_d = [], [], [], []

single.append(np.loadtxt('data/single4a4s100x.txt', skiprows=2))
single.append(np.loadtxt('data/single8a4s100x.txt', skiprows=2))
single.append(np.loadtxt('data/single16a4s1x.txt', skiprows=2))
single.append(np.loadtxt('data/single16a4s100x.txt', skiprows=2))
single.append(np.loadtxt('data/single16a6s10x.txt', skiprows=2))

double.append(np.loadtxt('data/double4a25d4s1x.txt', skiprows=2))
double.append(np.loadtxt('data/double4a25d4s100x.txt', skiprows=2))
double.append(np.loadtxt('data/double4a25d4s100x(2).txt', skiprows=2))
double.append(np.loadtxt('data/double4a50d4s100x.txt', skiprows=2))
double.append(np.loadtxt('data/double8a25d4s100x.txt', skiprows=2))

for i in range(5):
    while (Decimal((float)(single[i][0][0])) == Decimal('0.0')): single[i] = np.delete(single[i], (0), axis=0)
    while (Decimal((float)(double[i][0][0])) == Decimal('0.0')): double[i] = np.delete(double[i], (0), axis=0)
    single, double = np.array(single), np.array(double)
    
for i in range(5): 
    #u_s.append([finderror(single[i][j,1], a_slow) for j in range(len(single[i]))])
    #u_d.append([finderror(double[i][j,1], a_slow) for j in range(len(double[i]))])
    u_s.append([0.01 for j in range(len(single[i]))])
    u_d.append([0.1 for j in range(len(double[i]))])
    #for j in range(len(double[i])): double[i][j,0] = np.abs(double[i][j,0])

single, double, u_s, u_d = np.array(single), np.array(double), np.array(u_s), np.array(u_d)

wavelength = 650 * 10**(-9)     #650nm (red) light
length_s = 0.783                #distance from the sensor aperture to the laser aperture, single slit
length_d = 0.745                #distance from the sensor aperture to the laser aperture, double slit
I_s = np.array([0.27158, 1.14082, 0.02716, 3.95709, 0.07018])       #maximum intensity in corresponding single data
I_d = np.array([0.00766, 0.17700, 0.67458, 0.71563, 3.30389])       #maximum intensity in corresponding double data
#offset_s = np.array([0.06889, 0.06900, 0.06694, 0.06705, 0.07578])  #offset of maximum in corresponding single data
#offset_d = np.array([0.06939, 0.06755, 0.06939, 0.06817, 0.06928])  #offset of maximum in corresponding double data
offset_s = np.array([0.0694213, 0.0694508, 0.0675186, 0.0757648, 0.0680048])
offset_d = np.array([0.0697878, 0.0679757, 0.0693881, 0.0691909, 0.0692345])

In [36]:
#Graph the single slit diffraction patterns
makegraph(single[0][:,0], single[0][:,1], single_title+', a=0.04mm', 'single4a4s100x')
makegraph(single[1][:,0], single[1][:,1], single_title+', a=0.08mm', 'single8a4s100x')
makegraph(single[2][:,0], single[2][:,1], single_title+', a=0.16mm', 'single16a4s1x')
makegraph(single[3][:,0], single[3][:,1], single_title+', a=0.16mm', 'single16a4s100x')
makegraph(single[4][:,0], single[4][:,1], single_title+', a=0.16mm', 'single16a6s10x')

#Graph the double slit interference patterns
makegraph(double[0][:,0], double[0][:,1], double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s1x')
makegraph(double[1][:,0], double[1][:,1], double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s100x')
makegraph(double[2][:,0], double[2][:,1], double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s100x(2)')
makegraph(double[3][:,0], double[3][:,1], double_title+', a=0.04mm, d=0.50mm', 'double4a50d4s100x')
makegraph(double[4][:,0], double[4][:,1], double_title+', a=0.08mm, d=0.25mm', 'double8a25d4s100x')

In [72]:
#Setting up constants for curve fit analysis
popt_s, pcov_s = [0] * 5, [0] * 5
popt_d, pcov_d = [0] * 5, [0] * 5

for i in range(5): 
    I, offset, length = I_s[i], offset_s[i], length_s
    popt_s[i], pcov_s[i] = curve_fit(intensity_s, single[i][:,0], single[i][:,1], sigma=u_s[i])
    I, offset, length = I_d[i], offset_d[i], length_d
    popt_d[i], pcov_d[i] = curve_fit(intensity_d, double[i][:,0], double[i][:,1], sigma=u_d[i])
    
popt_s, pcov_s = np.array(popt_s), np.array(pcov_s)
popt_d, pcov_d = np.array(popt_d), np.array(pcov_d)

print('a:\n', popt_s, '\n\n', 'pcov:\n', pcov_s)
print('\n')
print('a, d:\n', popt_d, '\n\n', 'pcov:\n', pcov_d)

a:
 [[-0.55983534]
 [ 1.01319165]
 [-0.59137976]
 [ 1.25409195]
 [ 1.00807835]] 

 pcov:
 [[[  98.5207614 ]]

 [[3716.48070111]]

 [[  75.76476405]]

 [[ 958.61709973]]

 [[ 997.07583432]]]


a, d:
 [[-54.13355318   7.03108375]
 [  1.10515088   0.93515548]
 [ -1.65450951  -2.54896634]
 [  1.05655072   0.78351671]
 [ -0.11448647 -43.51650486]] 

 pcov:
 [[[ 1.23491717e+11  1.48343324e+10]
  [ 1.48343324e+10  1.10456423e+11]]

 [[ 1.18976837e+04 -3.48107136e+03]
  [-3.48107136e+03  2.51954596e+03]]

 [[ 3.45761614e+03  1.41154490e+02]
  [ 1.41154490e+02  7.39141054e+03]]

 [[ 5.71561109e+03  2.27971903e+03]
  [ 2.27971903e+03  1.29965892e+03]]

 [[ 6.21853523e-01  9.58132659e-01]
  [ 9.58132659e-01  1.61648571e+00]]]


In [67]:
#Graph the single slit data with best fit
makegraphfit(0, single_title+', a=0.04mm', 'single4a4s100xfit', 'single', 0.04*10**(-3), u=u_s[0])
makegraphfit(1, single_title+', a=0.08mm', 'single8a4s100xfit', 'single', 0.08*10**(-3), u=u_s[1])
makegraphfit(2, single_title+', a=0.16mm', 'single16a4s1xfit', 'single', 0.04*10**(-3), u=u_s[2])
makegraphfit(3, single_title+', a=0.16mm', 'single16a4s100xfit', 'single', 0.16*10**(-3), u=u_s[3])
makegraphfit(4, single_title+', a=0.16mm', 'single16a6s10xfit', 'single', 0.04*10**(-3), u=u_s[4])

#Graph the double slit data with best fit
makegraphfit(0, double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s1xfit', 'double', (0.00004, 0.00025), u=u_d[0])
makegraphfit(1, double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s100xfit', 'double', (0.00004, 0.00025), u=u_d[1])
makegraphfit(2, double_title+', a=0.04mm, d=0.25mm', 'double4a25d4s100x(2)fit', 'double', (0.00004, 0.00025), u=u_d[2])
makegraphfit(3, double_title+', a=0.04mm, d=0.50mm', 'double4a50d4s100xfit', 'double', (0.00004, 0.00050), u=u_d[3])
makegraphfit(4, double_title+', a=0.08mm, d=0.25mm', 'double8a25d4s100xfit', 'double', (0.00008, 0.00025), u=u_d[4])

In [66]:
#Reduced chi squared

a_s = np.array([0.00004, 0.00008, 0.00004, 0.00016, 0.00004])
a_d = np.array([[0.00004, 0.00025], [0.00004, 0.00025], [0.00004, 0.00025], [0.00004, 0.00050], [0.00008, 0.00025]])

for i in range(5): 
    N_s, N_d, n_s, n_d = len(single[i]), len(double[i]), 1, 2
    I, offset, length = I_s[i], offset_s[i], length_s
    chi_s = np.sum([((single[i][j,1] - intensity_s(single[i][j,0], a_s[i]))/u_s[i][j])**2 for j in range(N_s)])/(N_s - n_s)
    I, offset, length = I_d[i], offset_d[i], length_d
    chi_d = np.sum([((double[i][j,1] - intensity_d(double[i][j,0], a_d[i][0], a_d[i][1]))/u_d[i][j])**2 for j in range(N_d)])/(N_d - n_d)
    print(chi_s,'\n',chi_d,'\n')

0.23880095861704087 
 0.002420969965283461 

1.0259733716065003 
 0.040423116291086705 

0.2394804279032715 
 0.07671379803448426 

200.53469633755185 
 0.19328256747714476 

0.22754105354015605 
 0.5421348532929947 

